## Import libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

## Load entire station table (KMA)

In [4]:
kma_stations_100km=pd.read_csv("/home/msseo/works/72.2025_Imsil_swarm/station_table/used_stations_100km.csv", sep=",")
kma_stations_100km.head()

  Network  Code  Latitude  Longitude  Elevation Sensor
0      KS   BAU   35.1027   127.5968      562.0     EL
1      KS  BLGA   36.1392   127.3032      105.0     HG
2      KS  BLLA   34.8646   127.4638       45.0     HG
3      KS  BUYB   36.2726   126.9206       59.0     HH
4      KS  CGPA   34.8768   126.9710      144.0     HG

## Select stations to use for detection and save as `*.csv` file

In [7]:
selected_stations=np.array(["CHOA", "GKSA", "IMSB", "JASA", "JEU2", "JLSA", "MALA", "NAWB", "SIDA", "SUCA", "TAIA"])
print(f"Number of stations: {len(selected_stations)}")

Number of stations: 11

In [9]:
detection_stations=pd.read_csv("./stations.csv", sep=",", names=["id", "network", "station", "channel", "latitude", "longitude", "unit", "component", "response"])
detection_stations

Empty DataFrame
Columns: [id, network, station, channel, latitude, longitude, unit, component, response]
Index: []

In [18]:
id_list, network_list, station_list, channel_list=[], [], [], []
stla_list, stlo_list,  unit_list, comp_list, resp_list=[], [], [], [], []

for code in selected_stations:
    network=kma_stations_100km[kma_stations_100km["Code"]==code].reset_index(drop=True)["Network"][0]
    channel=kma_stations_100km[kma_stations_100km["Code"]==code].reset_index(drop=True)["Sensor"][0]
    stla=kma_stations_100km[kma_stations_100km["Code"]==code].reset_index(drop=True)["Latitude"][0]
    stlo=kma_stations_100km[kma_stations_100km["Code"]==code].reset_index(drop=True)["Longitude"][0]
    comp="E,N,Z"
    id_=f"{network}.{code}..{channel}"
    
    if channel=="HG":
        unit="m/s**2"
    else:
        unit="m/s"
       
    id_list.append(id_)
    network_list.append(network)
    station_list.append(code)
    channel_list.append(channel)
    stla_list.append(stla)
    stlo_list.append(stlo)
    unit_list.append(unit)
    comp_list.append(comp)
    
detection_stations["id"]=id_list
detection_stations["network"]=network_list
detection_stations["station"]=station_list
detection_stations["channel"]=channel_list
detection_stations["latitude"]=stla_list
detection_stations["longitude"]=stlo_list
detection_stations["unit"]=unit_list
detection_stations["component"]=comp_list

In [19]:
detection_stations

,id,network,station,channel,latitude,longitude,unit,component,response
0,KS.CHOA..HG,KS,CHOA,HG,35.84070,127.11710,m/s**2,"E,N,Z",NaN
1,KS.GKSA..HG,KS,GKSA,HG,35.23040,127.22510,m/s**2,"E,N,Z",NaN
2,KS.IMSB..HH,KS,IMSB,HH,35.61250,127.28550,m/s,"E,N,Z",NaN
3,KS.JASA..HG,KS,JASA,HG,35.65700,127.52040,m/s**2,"E,N,Z",NaN
4,KS.JEU2..EL,KS,JEU2,EL,35.49330,126.92960,m/s,"E,N,Z",NaN
5,KS.JLSA..HG,KS,JLSA,HG,35.35750,127.64800,m/s**2,"E,N,Z",NaN
6,KS.MALA..HG,KS,MALA,HG,35.74450,127.34780,m/s**2,"E,N,Z",NaN
7,KS.NAWB..HH,KS,NAWB,HH,35.42130,127.39640,m/s,"E,N,Z",NaN
8,KS.SIDA..HG,KS,SIDA,HG,35.67362,127.14138,m/s**2,"E,N,Z",NaN
9,KS.SUCA..HG,KS,SUCA,HG,35.37360,127.13860,m/s**2,"E,N,Z",NaN
10,KS.TAIA..HG,KS,TAIA,HG,35.65070,126.93180,m/s**2,"E,N,Z",NaN

In [20]:
detection_stations.to_csv("./stations.csv", index=False)